// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvfa-2m1z-OidcHUXny9p0MhvRl7thaPg',
    appId: '1:226663249144:web:ad26b36aa24b065bbe370d',
    messagingSenderId: '226663249144',
    projectId: 'tap-scan-af594',
    authDomain: 'tap-scan-af594.firebaseapp.com',
    storageBucket: 'tap-scan-af594.appspot.com',
    measurementId: 'G-MTLD40L0KC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDMxUXanmW9nqKJ9cs34j_VDZRqmi1JJLA',
    appId: '1:226663249144:android:451a41b6a1415772be370d',
    messagingSenderId: '226663249144',
    projectId: 'tap-scan-af594',
    storageBucket: 'tap-scan-af594.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhM6Gh4WU828l16DEQETl52K7ON2UYV8w',
    appId: '1:226663249144:ios:58912bb6d0204df8be370d',
    messagingSenderId: '226663249144',
    projectId: 'tap-scan-af594',
    storageBucket: 'tap-scan-af594.appspot.com',
    iosBundleId: 'com.example.tapScan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhM6Gh4WU828l16DEQETl52K7ON2UYV8w',
    appId: '1:226663249144:ios:1764b37a1c4ac49cbe370d',
    messagingSenderId: '226663249144',
    projectId: 'tap-scan-af594',
    storageBucket: 'tap-scan-af594.appspot.com',
    iosBundleId: 'com.example.tapScan.RunnerTests',
  );
}
